# Generated by Django 3.2.9 on 2021-12-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parasite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.parasite'),
        ),
        migrations.AddField(
            model_name='parasite',
            name='picture',
            field=models.ImageField(default=None, upload_to='parasite_pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parasite',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='clinical_pictures'),
        ),
        migrations.AddField(
            model_name='post',
            name='parasite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.parasite'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('clinician', 'Clinician'), ('researcher', 'Researcher'), ('public', 'Public')], default='Public', max_length=50),
        ),
    ]
