# Generated by Django 3.2.9 on 2021-11-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0002_article_parasite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parasite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.parasite'),
        ),
    ]
