# Generated by Django 2.2.17 on 2021-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0004_auto_20211128_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parasite',
            name='picture',
            field=models.ImageField(null=True, upload_to='parasite_pic'),
        ),
    ]
