# Generated by Django 3.2.5 on 2021-11-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0004_auto_20211109_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Role',
        ),
    ]
