# Generated by Django 2.2.17 on 2021-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0005_remove_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parasite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.Parasite')),
            ],
        ),
    ]
