# Generated by Django 2.2.17 on 2021-11-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0006_auto_20211113_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parasite',
            options={'verbose_name_plural': 'Parasites'},
        ),
        migrations.AddField(
            model_name='parasite',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parasite',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
