# Generated by Django 2.2.17 on 2021-11-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0007_auto_20211127_0507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parasite',
            options={},
        ),
    ]
