# Generated by Django 3.2.9 on 2021-11-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0007_auto_20211115_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='parasite',
        ),
    ]
