# Generated by Django 2.2.17 on 2021-11-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0008_auto_20211127_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parasite',
            name='slug',
        ),
    ]
