# Generated by Django 3.2.9 on 2021-12-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0002_auto_20211218_1943'),
        ('parasitologyTool', '0008_auto_20211216_1833'),
    ]

    operations = [
    ]
