# Generated by Django 2.2.17 on 2021-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0011_remove_parasite_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasite',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
