# Generated by Django 3.2.9 on 2021-12-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0012_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
