# Generated by Django 2.2.17 on 2021-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0013_auto_20211127_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parasite',
            name='slug',
            field=models.SlugField(),
        ),
    ]
