# Generated by Django 3.2.9 on 2021-12-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0014_researchpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchPost',
        ),
    ]
