# Generated by Django 3.2.9 on 2021-12-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0015_delete_researchpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='clinical_pictures')),
                ('file', models.FileField(default=None, upload_to='files')),
                ('parasite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.parasite')),
            ],
        ),
    ]
