# Generated by Django 2.2.17 on 2022-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0018_parasite_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parasite',
            name='intro',
            field=models.CharField(max_length=3000),
        ),
    ]
