# Generated by Django 3.2.9 on 2022-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0020_auto_20220127_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, upload_to='clinical_pictures'),
        ),
    ]
