# Generated by Django 3.2.9 on 2022-01-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0021_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='research_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.researchpost'),
        ),
    ]
