# Generated by Django 3.2.9 on 2022-01-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0022_alter_photo_research_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ResearchImage',
        ),
        migrations.RemoveField(
            model_name='researchpost',
            name='image',
        ),
    ]
