# Generated by Django 3.2.9 on 2022-01-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0023_auto_20220127_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpost',
            name='file',
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='files')),
                ('research_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.researchpost')),
            ],
        ),
    ]
