# Generated by Django 3.2.9 on 2022-02-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0034_auto_20220209_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='clinical_post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.researchpost'),
        ),
    ]
