# Generated by Django 2.2.17 on 2022-02-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0041_auto_20220211_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
