# Generated by Django 3.2.9 on 2022-02-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0043_auto_20220219_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.userprofile'),
        ),
    ]
