# Generated by Django 3.2.9 on 2022-02-19 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0044_researchpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
