# Generated by Django 3.2.9 on 2022-03-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0047_auto_20220219_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='researchpost',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='ClinicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='clinical_pictures')),
                ('clinical_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.post')),
            ],
        ),
    ]
