# Generated by Django 3.2.9 on 2022-03-03 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parasitologyTool', '0048_auto_20220303_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpost',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='researchpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='researchpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
