# Generated by Django 3.2.9 on 2022-03-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0050_auto_20220307_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parasitologyTool.comment')),
            ],
        ),
    ]
