# Generated by Django 3.2.9 on 2022-03-14 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0052_auto_20220314_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='article',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
