# Generated by Django 3.2.9 on 2022-03-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitologyTool', '0055_alter_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
    ]
