variables:
    DJANGO_CONFIG: "test"

stages:
  - build
  - test

migrations-tests:
    image: python:3.8
    before_script:
    - pip3 install -r requirements.txt
    - cd cs28TeamProject
    when: on_success
    stage: build

    script:
    - python3 manage.py makemigrations
    - python3 manage.py makemigrations parasitologyTool
    - python3 manage.py migrate
    - python3 manage.py collectstatic --noinput
    - python3 manage.py check



django-tests:
  stage: test
  script:
    - python3 manage.py test
